import { AnalysisResult, StudyPlan } from './types';

export const MOCK_ANALYSIS: AnalysisResult = {
  subjectName: 'Computer Science Engineering',
  totalPapers: 8,
  totalQuestions: 192,
  years: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024],
  coveragePercent: 78,
  analyzedAt: new Date().toISOString(),
  questionTypeDistribution: {
    'MCQ': 72,
    'Short Answer': 48,
    'Long Answer': 40,
    'Numerical': 22,
    'Case Study': 10,
  },
  difficultyDistribution: {
    'Easy': 45,
    'Medium': 98,
    'Hard': 49,
  },
  syllabusGaps: [
    'Cloud Computing Security',
    'Quantum Computing Basics',
    'Blockchain Technology',
    'Edge Computing',
    'DevOps Practices',
  ],
  topics: [
    {
      topic: 'Data Structures & Algorithms',
      frequency: 52,
      yearWise: { 2017: 5, 2018: 6, 2019: 7, 2020: 6, 2021: 8, 2022: 7, 2023: 7, 2024: 6 },
      questionTypes: { 'MCQ': 18, 'Short Answer': 14, 'Long Answer': 12, 'Numerical': 8 },
      avgMarks: 8.5,
      difficulty: 'Hard',
      importanceScore: 95,
      priority: 'Critical',
      inSyllabus: true,
      syllabusUnit: 'Unit 2',
    },
    {
      topic: 'Operating Systems',
      frequency: 41,
      yearWise: { 2017: 4, 2018: 5, 2019: 5, 2020: 5, 2021: 6, 2022: 5, 2023: 6, 2024: 5 },
      questionTypes: { 'MCQ': 15, 'Short Answer': 12, 'Long Answer': 10, 'Numerical': 4 },
      avgMarks: 7.2,
      difficulty: 'Medium',
      importanceScore: 88,
      priority: 'Critical',
      inSyllabus: true,
      syllabusUnit: 'Unit 3',
    },
    {
      topic: 'Database Management Systems',
      frequency: 38,
      yearWise: { 2017: 4, 2018: 4, 2019: 5, 2020: 4, 2021: 5, 2022: 6, 2023: 5, 2024: 5 },
      questionTypes: { 'MCQ': 12, 'Short Answer': 10, 'Long Answer': 9, 'Numerical': 7 },
      avgMarks: 7.8,
      difficulty: 'Medium',
      importanceScore: 84,
      priority: 'Critical',
      inSyllabus: true,
      syllabusUnit: 'Unit 4',
    },
    {
      topic: 'Computer Networks',
      frequency: 33,
      yearWise: { 2017: 3, 2018: 4, 2019: 4, 2020: 4, 2021: 4, 2022: 5, 2023: 5, 2024: 4 },
      questionTypes: { 'MCQ': 10, 'Short Answer': 9, 'Long Answer': 8, 'Numerical': 6 },
      avgMarks: 6.5,
      difficulty: 'Medium',
      importanceScore: 78,
      priority: 'High',
      inSyllabus: true,
      syllabusUnit: 'Unit 5',
    },
    {
      topic: 'Software Engineering',
      frequency: 28,
      yearWise: { 2017: 3, 2018: 3, 2019: 3, 2020: 4, 2021: 4, 2022: 4, 2023: 4, 2024: 3 },
      questionTypes: { 'MCQ': 8, 'Short Answer': 8, 'Long Answer': 8, 'Case Study': 4 },
      avgMarks: 6.0,
      difficulty: 'Easy',
      importanceScore: 71,
      priority: 'High',
      inSyllabus: true,
      syllabusUnit: 'Unit 6',
    },
    {
      topic: 'Theory of Computation',
      frequency: 24,
      yearWise: { 2017: 2, 2018: 3, 2019: 3, 2020: 3, 2021: 3, 2022: 3, 2023: 4, 2024: 3 },
      questionTypes: { 'MCQ': 9, 'Short Answer': 7, 'Long Answer': 6, 'Numerical': 2 },
      avgMarks: 7.0,
      difficulty: 'Hard',
      importanceScore: 64,
      priority: 'High',
      inSyllabus: true,
      syllabusUnit: 'Unit 7',
    },
    {
      topic: 'Compiler Design',
      frequency: 20,
      yearWise: { 2017: 2, 2018: 2, 2019: 3, 2020: 2, 2021: 3, 2022: 3, 2023: 3, 2024: 2 },
      questionTypes: { 'MCQ': 7, 'Short Answer': 6, 'Long Answer': 5, 'Numerical': 2 },
      avgMarks: 6.8,
      difficulty: 'Hard',
      importanceScore: 56,
      priority: 'Medium',
      inSyllabus: true,
      syllabusUnit: 'Unit 8',
    },
    {
      topic: 'Computer Architecture',
      frequency: 18,
      yearWise: { 2017: 2, 2018: 2, 2019: 2, 2020: 2, 2021: 2, 2022: 3, 2023: 3, 2024: 2 },
      questionTypes: { 'MCQ': 6, 'Short Answer': 5, 'Long Answer': 5, 'Numerical': 2 },
      avgMarks: 5.5,
      difficulty: 'Medium',
      importanceScore: 49,
      priority: 'Medium',
      inSyllabus: true,
      syllabusUnit: 'Unit 1',
    },
    {
      topic: 'Digital Logic Design',
      frequency: 14,
      yearWise: { 2017: 2, 2018: 1, 2019: 2, 2020: 1, 2021: 2, 2022: 2, 2023: 2, 2024: 2 },
      questionTypes: { 'MCQ': 5, 'Short Answer': 4, 'Long Answer': 3, 'Numerical': 2 },
      avgMarks: 5.0,
      difficulty: 'Easy',
      importanceScore: 38,
      priority: 'Low',
      inSyllabus: true,
      syllabusUnit: 'Unit 1',
    },
    {
      topic: 'Artificial Intelligence',
      frequency: 12,
      yearWise: { 2017: 1, 2018: 1, 2019: 1, 2020: 2, 2021: 2, 2022: 2, 2023: 2, 2024: 1 },
      questionTypes: { 'MCQ': 4, 'Short Answer': 4, 'Long Answer': 4 },
      avgMarks: 6.2,
      difficulty: 'Hard',
      importanceScore: 35,
      priority: 'Low',
      inSyllabus: true,
      syllabusUnit: 'Unit 9',
    },
    {
      topic: 'Information Security',
      frequency: 10,
      yearWise: { 2017: 1, 2018: 1, 2019: 1, 2020: 1, 2021: 1, 2022: 2, 2023: 2, 2024: 1 },
      questionTypes: { 'MCQ': 4, 'Short Answer': 3, 'Long Answer': 3 },
      avgMarks: 5.8,
      difficulty: 'Medium',
      importanceScore: 28,
      priority: 'Low',
      inSyllabus: true,
      syllabusUnit: 'Unit 10',
    },
    {
      topic: 'Discrete Mathematics',
      frequency: 8,
      yearWise: { 2017: 1, 2018: 1, 2019: 1, 2020: 1, 2021: 1, 2022: 1, 2023: 1, 2024: 1 },
      questionTypes: { 'MCQ': 3, 'Short Answer': 3, 'Numerical': 2 },
      avgMarks: 4.5,
      difficulty: 'Medium',
      importanceScore: 22,
      priority: 'Low',
      inSyllabus: true,
      syllabusUnit: 'Unit 1',
    },
  ],
};

export const MOCK_STUDY_PLAN: StudyPlan = {
  totalWeeks: 6,
  generatedAt: new Date().toISOString(),
  weeks: [
    {
      weekNum: 1,
      label: 'Week 1 — Critical Topics Foundation',
      focusArea: 'Data Structures & Algorithms',
      days: [
        { day: 'Monday', topic: 'Arrays, Linked Lists, Stacks & Queues', priority: 'Critical', hours: 4, tasks: ['Review array operations', 'Practice linked list problems', 'Solve 10 DSA MCQs from past papers'] },
        { day: 'Tuesday', topic: 'Trees: BST, AVL, Heaps', priority: 'Critical', hours: 4, tasks: ['Study tree traversals', 'Practice heap operations', 'Solve previous year tree questions'] },
        { day: 'Wednesday', topic: 'Graphs: BFS, DFS, Shortest Path', priority: 'Critical', hours: 4, tasks: ['Dijkstra & Bellman-Ford algorithms', 'Practice graph problems', 'Mock test: Graph questions (2019-2022)'] },
        { day: 'Thursday', topic: 'Sorting & Searching Algorithms', priority: 'Critical', hours: 3, tasks: ['Time complexity analysis', 'QuickSort, MergeSort implementation', 'Practice numerical problems'] },
        { day: 'Friday', topic: 'Dynamic Programming & Greedy', priority: 'Critical', hours: 4, tasks: ['Classic DP problems (Knapsack, LCS)', 'Greedy algorithm patterns', 'Full paper practice (2023)'] },
        { day: 'Saturday', topic: 'DSA Revision + Mock Test', priority: 'Critical', hours: 3, tasks: ['Revise all DSA topics', 'Full mock test: 25 DSA questions', 'Review mistakes'] },
      ],
    },
    {
      weekNum: 2,
      label: 'Week 2 — Operating Systems Deep Dive',
      focusArea: 'Operating Systems',
      days: [
        { day: 'Monday', topic: 'Process Management & Scheduling', priority: 'Critical', hours: 4, tasks: ['Process states and PCB', 'CPU scheduling algorithms (FCFS, SJF, Round Robin)', 'Solve scheduling numerical problems'] },
        { day: 'Tuesday', topic: 'Memory Management', priority: 'Critical', hours: 4, tasks: ['Paging and segmentation', 'Virtual memory concepts', 'Page replacement algorithms'] },
        { day: 'Wednesday', topic: 'Deadlocks & Synchronization', priority: 'Critical', hours: 3, tasks: ['Banker\'s algorithm', 'Semaphores & mutex', 'Producer-consumer problems'] },
        { day: 'Thursday', topic: 'File Systems & I/O', priority: 'High', hours: 3, tasks: ['File allocation methods', 'Disk scheduling algorithms', 'I/O management'] },
        { day: 'Friday', topic: 'Database Management Systems — Start', priority: 'Critical', hours: 4, tasks: ['ER diagrams and normalization', 'SQL queries from past papers', 'ACID properties'] },
        { day: 'Saturday', topic: 'OS Full Revision & Past Papers', priority: 'Critical', hours: 3, tasks: ['OS mock test (2020-2024)', 'DBMS SQL practice', 'Review error patterns'] },
      ],
    },
    {
      weekNum: 3,
      label: 'Week 3 — DBMS & Computer Networks',
      focusArea: 'Database Management & Networks',
      days: [
        { day: 'Monday', topic: 'SQL Advanced + Transactions', priority: 'Critical', hours: 4, tasks: ['Complex SQL queries', 'Transaction management & isolation levels', 'Concurrency control'] },
        { day: 'Tuesday', topic: 'Indexing & Query Optimization', priority: 'High', hours: 3, tasks: ['B-tree and hash indexes', 'Query execution plans', 'Relational algebra'] },
        { day: 'Wednesday', topic: 'Computer Networks — Layers 1-3', priority: 'High', hours: 4, tasks: ['OSI model and TCP/IP', 'Physical and data link layer', 'IP addressing & subnetting'] },
        { day: 'Thursday', topic: 'Transport & Application Layers', priority: 'High', hours: 3, tasks: ['TCP vs UDP', 'HTTP, FTP, DNS protocols', 'Socket programming concepts'] },
        { day: 'Friday', topic: 'Routing Protocols & Security', priority: 'High', hours: 3, tasks: ['RIP, OSPF, BGP', 'Network security basics', 'Firewall and encryption'] },
        { day: 'Saturday', topic: 'DBMS + Networks Mock Test', priority: 'High', hours: 3, tasks: ['Combined mock test', 'Numerical problems revision', 'Gap analysis'] },
      ],
    },
    {
      weekNum: 4,
      label: 'Week 4 — Software Engineering & Theory of Computation',
      focusArea: 'SE, TOC & Compiler Design',
      days: [
        { day: 'Monday', topic: 'SDLC Models & Agile', priority: 'High', hours: 3, tasks: ['Waterfall, Spiral, Agile', 'UML diagrams', 'Software metrics'] },
        { day: 'Tuesday', topic: 'Software Testing & Quality', priority: 'High', hours: 3, tasks: ['Black box vs white box testing', 'Test case design', 'Software quality models'] },
        { day: 'Wednesday', topic: 'Theory of Computation — Automata', priority: 'High', hours: 4, tasks: ['DFA, NFA construction', 'Regular expressions', 'Context-free grammars'] },
        { day: 'Thursday', topic: 'Turing Machines & Decidability', priority: 'High', hours: 3, tasks: ['TM design problems', 'Halting problem', 'Complexity classes P, NP'] },
        { day: 'Friday', topic: 'Compiler Design — Lexical & Syntax', priority: 'Medium', hours: 3, tasks: ['Lexical analysis, tokens', 'LL and LR parsing', 'Parse tree construction'] },
        { day: 'Saturday', topic: 'SE + TOC + Compiler Mock Test', priority: 'High', hours: 3, tasks: ['Mixed mock test', 'Identify weak areas', 'Past papers 2018-2021'] },
      ],
    },
    {
      weekNum: 5,
      label: 'Week 5 — Computer Architecture & Remaining Topics',
      focusArea: 'Architecture, Digital Logic, AI',
      days: [
        { day: 'Monday', topic: 'Computer Architecture', priority: 'Medium', hours: 3, tasks: ['Instruction set architecture', 'Pipeline hazards', 'Cache memory'] },
        { day: 'Tuesday', topic: 'Digital Logic Design', priority: 'Low', hours: 2, tasks: ['Boolean algebra', 'Combinational circuits', 'Flip-flops and counters'] },
        { day: 'Wednesday', topic: 'Artificial Intelligence Basics', priority: 'Low', hours: 2, tasks: ['Search algorithms (A*, BFS)', 'Knowledge representation', 'Machine learning overview'] },
        { day: 'Thursday', topic: 'Information Security', priority: 'Low', hours: 2, tasks: ['Encryption (RSA, AES)', 'Network attacks & prevention', 'Digital signatures'] },
        { day: 'Friday', topic: 'Discrete Mathematics', priority: 'Low', hours: 2, tasks: ['Graph theory', 'Combinatorics', 'Logic and proofs'] },
        { day: 'Saturday', topic: 'Comprehensive Mixed Test', priority: 'Medium', hours: 4, tasks: ['Full syllabus mock test', 'Review all low-priority areas', 'Identify final gaps'] },
      ],
    },
    {
      weekNum: 6,
      label: 'Week 6 — Revision & Exam Readiness',
      focusArea: 'Full Revision & Practice Tests',
      days: [
        { day: 'Monday', topic: 'DSA + OS Final Revision', priority: 'Critical', hours: 5, tasks: ['Quick revision notes', 'High-yield formula sheet', 'Practice 30 mixed MCQs'] },
        { day: 'Tuesday', topic: 'DBMS + Networks Final Revision', priority: 'Critical', hours: 4, tasks: ['SQL quick practice', 'Network diagrams revision', 'Previous year 2023-2024 papers'] },
        { day: 'Wednesday', topic: 'Full Mock Exam 1', priority: 'Critical', hours: 5, tasks: ['Simulate real exam conditions (3 hours)', 'Score and analyze results', 'Focus on wrong answers'] },
        { day: 'Thursday', topic: 'Weak Areas Targeted Practice', priority: 'High', hours: 4, tasks: ['Re-practice identified weak topics', 'Read conceptual explanations', 'Short video revision'] },
        { day: 'Friday', topic: 'Full Mock Exam 2 + Review', priority: 'Critical', hours: 5, tasks: ['Full paper simulation', 'Time management practice', 'Final weak area review'] },
        { day: 'Saturday', topic: 'Light Revision + Rest', priority: 'Medium', hours: 2, tasks: ['Quick formula sheets review', 'Confidence-boosting practice', 'Rest and prepare mentally'] },
      ],
    },
  ],
};

export const PRACTICE_QUESTIONS: Record<string, string[]> = {
  'Data Structures & Algorithms': [
    'Explain the time complexity of Quicksort in best, average, and worst case scenarios with proper justification.',
    'Implement a function to detect a cycle in a directed graph using DFS. Trace through an example.',
    'Given an array of integers, find the maximum sum subarray using Kadane\'s algorithm. What is the space complexity?',
  ],
  'Operating Systems': [
    'Compare and contrast preemptive and non-preemptive CPU scheduling algorithms with examples.',
    'Explain Banker\'s Algorithm for deadlock avoidance. Apply it to a system with 3 processes and 2 resource types.',
    'Describe the working of Least Recently Used (LRU) page replacement algorithm with a reference string example.',
  ],
  'Database Management Systems': [
    'Write an SQL query to find the second-highest salary from an Employee table without using LIMIT.',
    'Explain BCNF normalization with an example showing why 3NF may not be sufficient.',
    'What is a distributed transaction? Explain the two-phase commit protocol with a diagram.',
  ],
};
